[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# auto_detect_remappings = true # Recommended for automatically finding submodule remappings
# If you prefer to manage remappings manually, use the 'remappings' key instead.
# For example:
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
